name: Add Files to Release
on: workflow_dispatch

jobs:
  zip_file:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Get Repo
        uses: actions/checkout@v6.0.2
      - name: cd to datapack folder
        run: cd /home/runner/work/endgame-expanded/endgame-expanded/endgame_expanded
      - name: Create Zipfile
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r endgame_expanded.zip . -i *
      - name: Upload Artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          path: /home/runner/work/endgame-expanded/endgame-expanded/endgame_expanded/endgame_expanded.zip
          archive: false
          
        
