name: Add Files to Release
on: workflow_dispatch

jobs:
  zip_file:
    runs-on: ubuntu-latest
    steps:
      - name: Create Zipfile
        uses: TheDoctor0/zip-release@0.7.6
        with:
          filename: endgame_expanded.zip
          path: /home/runner/work/endgame-expanded/endgame-expanded/endgame_expanded
          directory: /home/runner/work/endgame-expanded/endgame-expanded/endgame_expanded
          type: zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          path: endgame_expanded.zip
          
        
